# Generated by Django 2.2 on 2022-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок статьи')),
                ('date', models.CharField(max_length=50, verbose_name='Дата создания')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('user_link', models.CharField(max_length=500, verbose_name='Ссылка на пользователя')),
            ],
        ),
    ]
