# Generated by Django 2.2 on 2022-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habr',
            name='user_link',
            field=models.URLField(verbose_name='Ссылка на пользователя'),
        ),
    ]
